'use client';

import { AnimatePresence, motion } from 'framer-motion';
import Image from 'next/image';
import { useState } from 'react';
import { fadeIn, textVariant } from '@/lib/animations';
import { projectCategories as categories, projects, type Project } from '@/lib/constants';

const categoryIcons: Record<string, string> = { All: '✦', Web: '◈', Mobile: '▣', AI: '✧', Backend: '⌘', Games: '◉' };

function Telemetry({ label, value }: { label: string; value: string }) {
  return <div className="min-w-0"><p className="truncate font-mono text-[9px] uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 truncate text-xs font-semibold text-cyan-100">{value}</p></div>;
}

function MissionCard({ project, index }: { project: Project; index: number }) {
  const missionId = String(index + 1).padStart(2, '0');
  return <motion.article layout variants={fadeIn('up', index * 0.06, 0.55)} initial="hidden" animate="show" exit={{ opacity: 0, scale: 0.94 }} className="group flex h-full flex-col overflow-hidden rounded-[1.75rem] border border-cyan-300/15 bg-[#080b18]/85 shadow-[0_18px_55px_rgba(8,47,73,.14)] backdrop-blur-xl transition-colors duration-300 hover:border-cyan-300/45 hover:shadow-[0_0_35px_rgba(34,211,238,.12)]">
    <div className="relative aspect-[16/9] overflow-hidden border-b border-cyan-300/10 bg-[#050816]"><Image src={project.image} alt={project.title} fill sizes="(max-width: 640px) 100vw, (max-width: 1280px) 50vw, 420px" className={`object-contain p-2 transition-transform duration-500 group-hover:scale-[1.03] ${project.comingSoon ? 'opacity-50 grayscale' : ''}`} /><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-[#080b18] via-transparent to-transparent" /><div className="absolute left-4 top-4 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.2em] text-cyan-200"><span className="h-2 w-2 rounded-full bg-cyan-300 shadow-[0_0_10px_rgba(103,232,249,.9)]" />Target // {missionId}</div>{project.featured && <span className="absolute right-4 top-4 rounded-full border border-yellow-300/60 bg-yellow-300 px-3 py-1 font-mono text-[10px] font-bold uppercase tracking-wider text-slate-950">Featured</span>}{!project.featured && project.isNew && <span className="absolute right-4 top-4 rounded-full border border-yellow-300/60 bg-yellow-300 px-3 py-1 font-mono text-[10px] font-bold uppercase tracking-wider text-slate-950">New signal</span>}{project.comingSoon && <span className="absolute right-4 top-4 rounded-full border border-purple-300/40 bg-purple-500/80 px-3 py-1 font-mono text-[10px] font-bold uppercase tracking-wider text-white">Incoming</span>}</div>
    <div className="flex flex-1 flex-col p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.25em] text-slate-500"><span className="text-sm text-cyan-300" aria-hidden="true">{categoryIcons[project.category[0]] ?? '•'}</span>Mission file / {project.category.join(' + ')}</p><h3 className="mt-2 text-xl font-black text-white">{project.title}</h3></div>{project.game && <span className="shrink-0 rounded-full border border-cyan-300/20 bg-cyan-300/[0.06] px-2 py-1 font-mono text-[10px] text-cyan-200">{project.game.dimension}</span>}</div><p className="mt-4 flex-1 text-sm leading-6 text-slate-400">{project.description}</p><div className="mt-5 grid grid-cols-4 gap-2 border-y border-cyan-300/10 py-3"><Telemetry label="Type" value={project.type} /><Telemetry label="Stack" value={project.stack.join(' · ')} /><Telemetry label="Status" value={project.status} /><Telemetry label="Year" value={String(project.year)} /></div>{project.game && <div className="mt-3 flex gap-3 font-mono text-[10px] uppercase tracking-wider text-slate-500"><span>Engine: <strong className="text-cyan-200">{project.game.engine}</strong></span><span>Genre: <strong className="text-cyan-200">{project.game.genre}</strong></span></div>}<div className="mt-5 flex flex-wrap gap-1.5">{project.tags.map((tag) => <span key={tag} className="rounded-md border border-cyan-300/10 bg-cyan-300/[0.04] px-2 py-1 font-mono text-[10px] text-cyan-200">{tag}</span>)}</div><div className="mt-6 flex flex-wrap gap-3"><a href={project.repo} target="_blank" rel="noopener noreferrer" className="flex-1 rounded-xl border border-cyan-300/40 bg-cyan-300/90 px-3 py-2.5 text-center font-mono text-xs font-bold uppercase tracking-wider text-slate-950 transition hover:bg-cyan-200">Source ↗</a>{project.demo && <a href={project.demo} target="_blank" rel="noopener noreferrer" className="flex-1 rounded-xl border border-cyan-300/20 bg-white/[0.05] px-3 py-2.5 text-center font-mono text-xs font-bold uppercase tracking-wider text-cyan-100 transition hover:bg-cyan-300/10">{project.demoLabel ?? 'Live Demo'} ↗</a>}{project.extraLinks?.map((link) => <a key={link.url} href={link.url} target="_blank" rel="noopener noreferrer" className="flex-1 rounded-xl border border-cyan-300/20 bg-white/[0.05] px-3 py-2.5 text-center font-mono text-xs font-bold uppercase tracking-wider text-cyan-100 transition hover:bg-cyan-300/10">{link.label} ↗</a>)}</div></div>
  </motion.article>;
}

export default function ProjectsSection() {
  const [activeCategory, setActiveCategory] = useState('All');
  const filteredProjects = [...projects].filter((project) => activeCategory === 'All' || project.category.includes(activeCategory)).sort((a, b) => Number(b.featured) - Number(a.featured) || b.year - a.year);
  return <section className="relative overflow-hidden px-4 py-24 sm:px-6 lg:px-8"><div className="pointer-events-none absolute left-1/2 top-0 h-[360px] w-[760px] -translate-x-1/2 rounded-full bg-cyan-900/15 blur-[140px]" /><div className="relative z-10 mx-auto max-w-7xl"><motion.header variants={textVariant()} initial="hidden" whileInView="show" viewport={{ once: true }} className="text-center"><p className="font-mono text-xs font-bold uppercase tracking-[0.45em] text-cyan-300">Project Galaxy / Mission Gallery</p><h2 className="mt-3 text-4xl font-black text-white sm:text-6xl">Mission Archive</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-slate-400">Completed builds and game missions mapped as navigable targets across the software universe.</p></motion.header><motion.div variants={fadeIn('up', 0.15, 0.8)} initial="hidden" whileInView="show" viewport={{ once: true }} className="relative mx-auto mt-12 flex max-w-5xl flex-wrap justify-center gap-2 py-4 sm:gap-3"><span className="pointer-events-none absolute left-0 right-0 top-1/2 h-px -translate-y-1/2 bg-gradient-to-r from-transparent via-cyan-300/25 to-transparent" />{categories.map((category) => <button key={category} onClick={() => setActiveCategory(category)} className={`relative z-10 rounded-full border px-4 py-2 text-xs font-semibold transition-all sm:px-5 sm:text-sm ${activeCategory === category ? 'border-cyan-300 bg-cyan-300 text-slate-950 shadow-[0_0_20px_rgba(103,232,249,.4)]' : 'border-cyan-300/15 bg-[#080b18]/90 text-slate-400 hover:border-cyan-300/50 hover:text-cyan-100'}`}><span className="mr-1.5" aria-hidden="true">{categoryIcons[category]}</span>{category}</button>)}</motion.div><motion.div layout className="mt-10 grid grid-cols-1 gap-6 sm:grid-cols-2 xl:grid-cols-3"><AnimatePresence mode="popLayout">{filteredProjects.map((project, index) => <MissionCard key={project.id} project={project} index={index} />)}</AnimatePresence></motion.div></div></section>;
}
